---
- name: prepare dir
  file:
    name: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ DATA_PATH }}/mongo"
  tags:
    - sync

- name: 复制 rpm 安装包
  copy: src=../files/rpms/{{ item }} dest=/tmp/{{ item }} mode=0644
  with_items:
    - mongodb-org-unstable-tools-4.1.8-1.el7.x86_64.rpm
    - mongodb-org-unstable-mongos-4.1.8-1.el7.x86_64.rpm
    - mongodb-org-unstable-shell-4.1.8-1.el7.x86_64.rpm
    - mongodb-org-unstable-server-4.1.8-1.el7.x86_64.rpm

- name: 安装依赖程序
  include: "{{ item }}"
  with_first_found:
    - "install_task.yml"
  tags: [mongodb]

- name: 安装 rpm
  yum:
    name: /tmp/{{ item }}
    state: present
  with_items:
    - mongodb-org-unstable-tools-4.1.8-1.el7.x86_64.rpm
    - mongodb-org-unstable-mongos-4.1.8-1.el7.x86_64.rpm
    - mongodb-org-unstable-shell-4.1.8-1.el7.x86_64.rpm
    - mongodb-org-unstable-server-4.1.8-1.el7.x86_64.rpm

- name: 构建service
  template:
    src: mongodb.service.j2
    dest: "/lib/systemd/system/mongod.service"
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload systemd

- name: 配置需要的资源
  include: configure.yml
  tags: [mongodb]

- name: 初始化认证
  include: auth_initialization.yml
  tags: [mongodb]

- name: 初始化副本集
  include: init_replicaset.yml
  when: ( MONGO_MASTER is defined and MONGO_MASTER )
  tags: [mongodb]

- name: 启动 mongo
  shell: systemctl daemon-reload && systemctl enable mongod.service && systemctl restart mongod.service
