---
- name: Install EPEL release repository
  package:
    name: epel-release
    state: present

- name: Install numactl package
  yum:
    name: numactl
    state: present
    lock_timeout: 180

- name: Install PIP
  yum:
    name:
      - python-devel
      - python-pip
    lock_timeout: 180

- name: Install PyMongo from PIP
  pip:
    name: pymongo
    version: 3.7.1
